/* @flow */

// REST
export const GET_THREE_ASSET = 'GET_THREE_ASSET';
export const THREE_ASSET_LOADED = 'THREE_ASSET_LOADED';
export const THREE_METADATA_LOADED = 'THREE_METADATA_LOADED';

// Meshes
export const LOAD_MESH = 'LOAD_MESH';
export const UPDATE_MESH_LOAD_PROGRESS = 'UPDATE_MESH_LOAD_PROGRESS';
export const MESH_LOAD_ERROR = 'MESH_LOAD_ERROR';
export const MESH_LOADED = 'MESH_LOADED';
export const LOAD_LOCAL_TEXTURE_ASSET = "LOAD_LOCAL_TEXTURE_ASSET";
export const LOCAL_TEXTURE_ASSET_LOADED = "LOCAL_TEXTURE_ASSET_LOADED";

// Textures
export const UPDATE_TEXTURE_LOAD_PROGRESS = 'UPDATE_TEXTURE_LOAD_PROGRESS';
export const TEXTURE_LOAD_ERROR = 'TEXTURE_LOAD_ERROR';
export const TEXTURE_LOADED = 'TEXTURE_LOADED';
export const LOAD_TEXTURE = 'LOAD_TEXTURE';

// Admin
export const AUTHENTICATE = 'AUTHENTICATE';
export const AUTHENTICATE_ATTEMPTED = 'AUTHENTICATE_ATTEMPTED';
export const LOGIN_USER = 'LOGIN_USER';
export const LOGOUT_USER = 'LOGOUT_USER';
export const USER_LOGGED_IN = 'USER_LOGGED_IN';
export const USER_LOGGED_OUT = 'USER_LOGGED_OUT';

export const ADD_USER = 'ADD_USER';
export const USER_ADDED = 'USER_ADDED';
export const VERIFY_USER = 'VERIFY_USER';
export const USER_VERIFIED = 'USER_VERIFIED';
export const DELETE_USER = 'DELETE_USER';
export const USER_DELETED = 'USER_DELETED';
export const UPDATE_USER = 'UPDATE_USER';
export const USER_UPDATED = 'USER_UPDATED';

export const LOGIN_ERROR = 'LOGIN_ERROR';
export const REMOVE_LOGIN_ERROR = 'REMOVE_LOGIN_ERROR';
export const USER_AUTHENTICATED = 'USER_AUTHENTICATED';

export const GET_VIEWS = 'GET_VIEWS';
export const GET_VIEW = 'GET_VIEW';
export const GET_THREEFILE = 'GET_THREEFILE';
export const ADD_VIEW = 'ADD_VIEW';
export const DELETE_VIEW = 'DELETE_VIEW';
export const UPDATE_VIEW  = 'UPDATE_VIEW';

export const VIEW_ADDED = 'VIEW_ADDED';
export const VIEWS_LOADED = 'VIEWS_LOADED';
export const VIEW_LOADED = 'VIEW_LOADED';

// Settings
export const SAVE_VIEWER_SETTINGS = 'SAVE_VIEWER_SETTINGS';
export const LOAD_VIEWER_SETTINGS = 'LOAD_VIEWER_SETTINGS';
export const VIEWER_SETTINGS_SAVED = 'VIEWER_SETTINGS_SAVED';
export const VIEWER_SETTINGS_ERROR = 'VIEWER_SETTINGS_ERROR';
export const RESET_SAVE_STATUS = 'RESET_SAVE_STATUS';

// Converter
export const START_CONVERSION = 'START_CONVERSION';
export const CONVERSION_STARTED = 'CONVERSION_STARTED';
export const UPDATE_CONVERSION_PROGRESS = 'UPDATE_CONVERSION_PROGRESS';
export const CONVERSION_COMPLETE = 'CONVERSION_COMPLETE';
export const CONVERSION_ERROR = 'CONVERSION_ERROR';
export const RESTART_CONVERTER = 'RESTART_CONVERTER';

// Annotations
export const SAVE_ANNOTATION = "SAVE_ANNOTATION";
export const ANNOTATION_SAVED = "ANNOTATION_SAVED";
export const DELETE_ANNOTATION = "DELETE_ANNOTATION";
export const ANNOTATION_DELETED = "ANNOTATION_DELETED";
export const UPDATE_ANNOTATION = "UPDATE_ANNOTATION";
export const UPDATE_ANNOTATIONS_ORDER = "UPDATE_ANNOTATIONS_ORDER";
export const LOAD_ANNOTATIONS = "LOAD_ANNOTATIONS";
export const ANNOTATIONS_LOADED = "ANNOTATIONS_LOADED";
export const ANNOTATIONS_MERGED = "ANNOTATIONS_MERGED";
export const RESET_ANNOTATIONS_UPDATE_STATUS = "RESET_ANNOTATIONS_UPDATE_STATUS";
export const ANNOTATION_FOCUS_CHANGED = "ANNOTATION_FOCUS_CHANGED";